// ГОСТ 8724-2002, таблица 1: именно столбец «крупный», не максимальный доступный шаг.
const METRIC_COARSE_PITCH={1:.25,1.1:.25,1.2:.25,1.4:.3,1.6:.35,1.8:.35,2:.4,2.2:.45,2.5:.45,3:.5,3.5:.6,4:.7,4.5:.75,5:.8,6:1,7:1,8:1.25,9:1.25,10:1.5,11:1.5,12:1.75,14:2,16:2,18:2.5,20:2.5,22:2.5,24:3,27:3,30:3.5,33:3.5,36:4,39:4,42:4.5,45:4.5,48:5,52:5,56:5.5,60:5.5,64:6,68:6};
function coarseBadge(t){return t.system==='METRIC_GOST'&&METRIC_COARSE_PITCH[t.diameter_mm]===t.pitch_mm?'<span class="tag coarse-tag">Крупный шаг</span>':''}

const $=id=>document.getElementById(id), fmt=(x,n=3)=>x==null||Number.isNaN(+x)?'—':Number(x).toFixed(n).replace('.',',').replace(/,?0+$/,'');
let side='external', last=[], prevPage='reference', current=null, sort={key:'diameter_mm',dir:1};
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));$(id).classList.add('on');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.page===id));if(id!=='detail')prevPage=id;if(id==='reference')renderReference();scrollTo(0,0)}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$('ext').onclick=()=>{side='external';$('ext').classList.add('on');$('int').classList.remove('on');$('diaLabel').textContent='Измеренный наружный диаметр болта'};
$('int').onclick=()=>{side='internal';$('int').classList.add('on');$('ext').classList.remove('on');$('diaLabel').textContent='Измеренный диаметр отверстия гайки'};
$('tol').oninput=()=>$('tolv').textContent='±'+Number($('tol').value).toFixed(2).replace('.',',')+' мм';
function measureInfo(t,s){if(t.system==='METRIC_GOST'){let fs=gostFields(t,s);if(fs.length){let mins=fs.map(v=>s==='external'?v.major_min:v.minor_min),maxs=fs.map(v=>s==='external'?v.major_max:v.minor_max);return {ref:(Math.min(...mins)+Math.max(...maxs))/2,range:[Math.min(...mins),Math.max(...maxs)],field:fs.map(v=>v.field).join('/')}}}if(s==='external'){if(t.system==='UNIFIED'){let vals=Object.values(t.external||{}).filter(v=>v.major_min!=null&&v.major_max!=null);if(vals.length){let mn=Math.min(...vals.map(v=>v.major_min)),mx=Math.max(...vals.map(v=>v.major_max));return {ref:(mn+mx)/2,range:[mn,mx]}}}return {ref:t.diameter_mm,range:null}}else{if(t.system==='UNIFIED'){let vals=Object.values(t.internal||{}).filter(v=>v.minor_min!=null&&v.minor_max!=null);if(vals.length){let mn=Math.min(...vals.map(v=>v.minor_min)),mx=Math.max(...vals.map(v=>v.minor_max));return {ref:(mn+mx)/2,range:[mn,mx]}}}return {ref:t.basic?.d1??t.diameter_mm,range:null}}}
function distanceTo(d,m){return m.range?(d<m.range[0]?m.range[0]-d:d>m.range[1]?d-m.range[1]:0):Math.abs(d-m.ref)}
function classBadges(t,d,s){if(t.system==='METRIC_GOST'){let fs=gostFields(t,s);return fs.map(v=>{let a=s==='external'?v.major_min:v.minor_min,b=s==='external'?v.major_max:v.minor_max,ok=d>=a&&d<=b;return `<span class="badge ${ok?'yes':'no'}">${v.field} ${ok?'✓':'—'}</span>`}).join('')}if(t.system!=='UNIFIED')return '';let o=t[s]||{};return Object.entries(o).filter(([c])=>['2A','3A','2B','3B'].includes(c)).map(([c,v])=>{let a=s==='internal'?v.minor_min:v.major_min,b=s==='internal'?v.minor_max:v.major_max,ok=a!=null&&b!=null&&d>=a&&d<=b;return `<span class="badge ${ok?'yes':'no'}">${c} ${ok?'✓':'—'}</span>`}).join('')}
function scorePct(dd,dp,td,tp){let nd=dd/td,np=dp/tp;let penalty=.58*nd+.42*np;return Math.max(0,Math.min(100,Math.round(100*(1-penalty*.78))))}
function search(){let d=+$('dia').value,p=$('pitch').value?+$('pitch').value:($('tpi').value?25.4/+$('tpi').value:NaN),td=+$('tol').value,tp=Math.max(.025,td*.45);if(!d||!p){$('results').innerHTML='<div class="count">Введите диаметр и шаг или TPI.</div>';return}let a=THREADS.map(t=>{let m=measureInfo(t,side),dd=distanceTo(d,m),dp=Math.abs(p-t.pitch_mm);return {t,m,dd,dp,s:dd/td+dp/tp,pct:scorePct(dd,dp,td,tp)}}).filter(x=>x.dd<=td&&x.dp<=tp).sort((a,b)=>a.s-b.s).slice(0,8);last=a;$('results').innerHTML=`<div class="count">Найдено ${a.length}. Показаны ближайшие варианты.</div>`+a.map((x,i)=>`<div class="result" onclick="openFinderDetail(${i})"><div class="rhead"><div><span class="tag">${x.t.system==='METRIC_GOST'?'ГОСТ · M':'ASME · '+x.t.series}</span><span class="name">${x.t.designation}</span>${coarseBadge(x.t)}</div><span class="score">${x.pct}%</span></div><div class="dims">${side==='internal'?('Отверстие '+(x.m.range?fmt(x.m.range[0])+'…'+fmt(x.m.range[1]):'≈ '+fmt(x.m.ref))+' мм · номинал '+fmt(x.t.diameter_mm)+' мм'):('Ø '+fmt(x.t.diameter_mm)+' мм')} · P ${fmt(x.t.pitch_mm)} мм · ${fmt(x.t.tpi,2)} TPI</div><div class="delta">ΔØ <b>${fmt(x.dd)}</b> мм · ΔP <b>${fmt(x.dp)}</b> мм</div><div class="badges">${classBadges(x.t,d,side)}</div></div>`).join('')}
$('go').onclick=search;function openFinderDetail(i){prevPage='finder';openDetail(last[i].t)}
function sourceShort(t){return t.system==='METRIC_GOST'?'ГОСТ 8724 / 24705 / 16093':'ASME B1.1-2024'}
function populateSeries(){let vals=[...new Set(THREADS.map(t=>t.series))].sort();$('series').innerHTML='<option value="ALL">Все серии</option>'+vals.map(x=>`<option>${x}</option>`).join('')};populateSeries();
function measureText(t,s){let m=measureInfo(t,s);return m.range?fmt(m.range[0])+'…'+fmt(m.range[1]):'≈ '+fmt(m.ref)}
function activeNear(){let d=parseFloat($('nearD').value),p=parseFloat($('nearP').value),t=parseFloat($('nearT').value);return {d,p,t,any:Number.isFinite(d)||Number.isFinite(p)||Number.isFinite(t)}}
function closeness(t,s,n){let vals=[];if(Number.isFinite(n.d)){let x=measureInfo(t,s).ref;vals.push(Math.abs(x-n.d)/Math.max(.05,Math.abs(n.d)*.01))}if(Number.isFinite(n.p))vals.push(Math.abs(t.pitch_mm-n.p)/Math.max(.02,Math.abs(n.p)*.02));if(Number.isFinite(n.t))vals.push(Math.abs(t.tpi-n.t)/Math.max(.5,Math.abs(n.t)*.02));return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0}
function refData(){let q=$('q').value.trim().toLowerCase(),sys=$('sys').value,ser=$('series').value,s=$('refSide').value,n=activeNear();let a=THREADS.filter(t=>(sys==='ALL'||t.system===sys)&&(ser==='ALL'||t.series===ser)&&(!q||[t.designation,t.series,t.source,String(t.tpi),String(t.diameter_mm)].join(' ').toLowerCase().includes(q)));if(n.any){a.sort((A,B)=>closeness(A,s,n)-closeness(B,s,n)||Math.abs(measureInfo(A,s).ref-(n.d||measureInfo(A,s).ref))-Math.abs(measureInfo(B,s).ref-(n.d||measureInfo(B,s).ref)))}else{let val=(t,k)=>k==='measure'?measureInfo(t,s).ref:t[k];a.sort((A,B)=>{let va=val(A,sort.key),vb=val(B,sort.key);if(typeof va==='number'&&typeof vb==='number')return (va-vb)*sort.dir;return String(va??'').localeCompare(String(vb??''),'ru')*sort.dir})}return {a,s,n}}
function range(v,a,b){return v&&v[a]!=null&&v[b]!=null?fmt(v[a])+'…'+fmt(v[b]):'—'}
function tolCell(t,s,kind){if(t.system==='METRIC_GOST'){let fs=gostFields(t,s);if(!fs.length)return '—';if(kind==='major')return s==='external'?'<span class="multi">'+fs.map(v=>`<b>${v.field}</b> ${fmt(v.major_min)}…${fmt(v.major_max)}`).join('<br>')+'</span>':'—';if(kind==='pitch')return '<span class="multi">'+fs.map(v=>`<b>${v.field}</b> ${fmt(v.pitch_min)}…${fmt(v.pitch_max)}`).join('<br>')+'</span>';if(kind==='minor')return s==='internal'?'<span class="multi">'+fs.map(v=>`<b>${v.field}</b> ${fmt(v.minor_min)}…${fmt(v.minor_max)}`).join('<br>')+'</span>':(t.basic?.d1!=null?'<span class="multi"><b>d₁ ном.</b> '+fmt(t.basic.d1)+'</span>':'—');return '—'}let o=t[s]||{}, cs=s==='external'?['2A','3A']:['2B','3B'];let keys=kind==='major'?['major_min','major_max']:kind==='pitch'?['pitch_min','pitch_max']:['minor_min','minor_max'];return '<span class="multi">'+cs.map(c=>o[c]?'<b>'+c+'</b> '+range(o[c],keys[0],keys[1]):'').filter(Boolean).join('<br>')+'</span>'}
function renderReference(){
 let data=refData(),a=data.a,s=data.s,n=data.n,mobile=window.matchMedia&&window.matchMedia('(max-width:760px)').matches;
 let limit=mobile?120:240,shown=a.slice(0,limit),more=a.length>shown.length;
 $('refCount').innerHTML=`Найдено ${a.length} из ${THREADS.length} записей`+(more?` · отображены первые ${shown.length}`:'')+(n.any?'<span class="nearMode">↔ по близости: все заполненные поля</span>':'');
 if(mobile){
  $('refHead').innerHTML='';$('refBody').innerHTML='';
  $('mobileRef').innerHTML=shown.length?shown.map(t=>`<div class="mobileRow" data-thread-id="${t.id}"><div class="mrTop"><b>${t.designation}</b>${coarseBadge(t)}<span class="tag">${t.system==='METRIC_GOST'?'ГОСТ':t.series}</span></div><div class="mrDims">${s==='internal'?'D₁ '+measureText(t,s)+' · ':''}Ø ${fmt(t.diameter_mm)} · P ${fmt(t.pitch_mm)} · ${fmt(t.tpi,2)} TPI</div><div class="mrTol">${t.system==='UNIFIED'?(s==='external'?'2A / 3A':'2B / 3B'):(s==='external'?'6g / 6h':'6H / 7H / 8H')+' · d₂ '+fmt(t.basic&&t.basic.d2)+' · d₁ '+fmt(t.basic&&t.basic.d1)}</div></div>`).join(''):'<div class="empty">Ничего не найдено</div>';return;
 }
 $('mobileRef').innerHTML='';
 let h=s==='external'?`<tr><th data-sort="designation">Обозначение</th><th data-sort="series">Серия</th><th data-sort="diameter_mm" class="num">d ном., мм</th><th data-sort="pitch_mm" class="num">P, мм</th><th data-sort="tpi" class="num">TPI</th><th>d, пределы мм</th><th>d₂, пределы / ном.</th><th>d₁, пределы / ном.</th><th data-sort="source">Стандарт</th></tr>`:`<tr><th data-sort="designation">Обозначение</th><th data-sort="series">Серия</th><th data-sort="diameter_mm" class="num">D ном., мм</th><th data-sort="measure" class="num">D₁ измеряемый, мм</th><th data-sort="pitch_mm" class="num">P, мм</th><th data-sort="tpi" class="num">TPI</th><th>D₂, пределы / ном.</th><th>D₁, пределы / ном.</th><th data-sort="source">Стандарт</th></tr>`;
 $('refHead').innerHTML=h;
 $('refBody').innerHTML=shown.length?shown.map(t=>s==='external'?`<tr data-thread-id="${t.id}"><td><b>${t.designation}</b>${coarseBadge(t)}</td><td>${t.series}</td><td class="num">${fmt(t.diameter_mm)}</td><td class="num">${fmt(t.pitch_mm)}</td><td class="num">${fmt(t.tpi,2)}</td><td>${tolCell(t,s,'major')}</td><td>${tolCell(t,s,'pitch')}</td><td>${tolCell(t,s,'minor')}</td><td>${sourceShort(t)}</td></tr>`:`<tr data-thread-id="${t.id}"><td><b>${t.designation}</b>${coarseBadge(t)}</td><td>${t.series}</td><td class="num">${fmt(t.diameter_mm)}</td><td class="num">${measureText(t,s)}</td><td class="num">${fmt(t.pitch_mm)}</td><td class="num">${fmt(t.tpi,2)}</td><td>${tolCell(t,s,'pitch')}</td><td>${tolCell(t,s,'minor')}</td><td>${sourceShort(t)}</td></tr>`).join(''):`<tr><td colspan="9" class="empty">Ничего не найдено</td></tr>`;
 document.querySelectorAll('.refTable th[data-sort]').forEach(th=>th.onclick=()=>{let k=th.dataset.sort;if(sort.key===k)sort.dir*=-1;else{sort.key=k;sort.dir=1}renderReference()});
}
$('refBody').addEventListener('click',e=>{let row=e.target.closest('tr[data-thread-id]');if(row)openRefDetail(row.dataset.threadId)});
$('mobileRef').addEventListener('click',e=>{let row=e.target.closest('.mobileRow[data-thread-id]');if(row)openRefDetail(row.dataset.threadId)});
let renderTimer=0;function scheduleReferenceRender(){clearTimeout(renderTimer);renderTimer=setTimeout(renderReference,90)}
['q','sys','series','refSide','nearD','nearP','nearT'].forEach(id=>$(id).addEventListener(id==='q'||id.indexOf('near')===0?'input':'change',id==='q'||id.indexOf('near')===0?scheduleReferenceRender:renderReference));$('clearRef').onclick=()=>{$('q').value='';$('sys').value='ALL';$('series').value='ALL';$('nearD').value='';$('nearP').value='';$('nearT').value='';sort={key:'diameter_mm',dir:1};renderReference()};
function openRefDetail(id){prevPage='reference';openDetail(THREADS.find(t=>t.id===id))}
function openDetail(t){current=t;showPage('detail');prevPage=prevPage==='detail'?'reference':prevPage;let unified=t.system==='UNIFIED',basic=t.basic;let facts=`<div class="facts"><div class="fact"><small>Номинальный Ø</small><b>${fmt(t.diameter_mm)} мм</b></div><div class="fact"><small>Шаг P</small><b>${fmt(t.pitch_mm)} мм</b></div><div class="fact"><small>TPI</small><b>${fmt(t.tpi,2)}</b></div><div class="fact"><small>Угол профиля</small><b>${t.angle}°</b></div></div>`;let sizePane=basic?`<table class="dtable"><tr><th>Параметр</th><th>Размер, мм</th></tr><tr><td>d / D</td><td>${fmt(t.diameter_mm)}</td></tr><tr><td>d₂ / D₂</td><td>${fmt(basic.d2)}</td></tr><tr><td>d₁ / D₁</td><td>${fmt(basic.d1)}</td></tr><tr><td>d₃</td><td>${fmt(basic.d3)}</td></tr></table>`:`<div class="note">Для Unified предельные размеры приведены на вкладке «Допуски» по классам.</div>`;let tolPane=unified?limitsTables(t):metricLimitsTable(t);let prof=`<div class="profile"><svg viewBox="0 0 620 230" role="img"><path d="M25 170 L95 70 L165 170 L235 70 L305 170 L375 70 L445 170 L515 70 L585 170" fill="none" stroke="#315f91" stroke-width="4"/><line x1="95" y1="45" x2="235" y2="45" stroke="#67788a"/><path d="M95 45 l12 -6 v12zM235 45 l-12 -6 v12z" fill="#67788a"/><text x="154" y="34" font-size="18">P = ${fmt(t.pitch_mm)} мм</text><path d="M78 95 A34 34 0 0 1 112 95" fill="none" stroke="#67788a"/><text x="82" y="117" font-size="15">60°</text><line x1="25" y1="185" x2="585" y2="185" stroke="#a9b3bd" stroke-dasharray="6 5"/><text x="25" y="215" font-size="14">Схема профиля условная, не в масштабе</text></svg></div>`;$('detailBody').innerHTML=`<div class="detailTop"><div><span class="tag">${unified?'ASME · '+t.series:'ГОСТ · M'}</span><div class="name" style="font-size:25px;margin-top:7px">${t.designation}</div>${coarseBadge(t)}</div></div>${facts}<div class="tabs"><button class="on" data-pane="size">Размеры</button><button data-pane="tol">Допуски</button><button data-pane="profile">Профиль</button></div><div class="detailPane" id="pane">${sizePane}</div><div class="source">Источник: ${t.source}${t.system==='METRIC_GOST'?' · ГОСТ 16093-2004':''}</div>`;let panes={size:sizePane,tol:tolPane,profile:prof};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('pane').innerHTML=panes[b.dataset.pane]})}
function metricLimitsTable(t){let ex=gostFields(t,'external'),ins=gostFields(t,'internal');if(!ex.length&&!ins.length)return `<div class="note">Для этого сочетания диаметра и шага поля допусков в текущем наборе не сформированы.</div>`;let rows=(fs,side)=>fs.map(v=>`<tr><td><b>${v.field}</b></td><td>${side==='external'?fmt(v.major_min)+' … '+fmt(v.major_max):fmt(v.minor_min)+' … '+fmt(v.minor_max)}</td><td>${fmt(v.pitch_min)} … ${fmt(v.pitch_max)}</td></tr>`).join('');return `<h3>Наружная резьба</h3><div style="overflow:auto"><table class="dtable"><tr><th>Поле</th><th>d, мм</th><th>d₂, мм</th></tr>${rows(ex,'external')}</table></div><h3>Внутренняя резьба</h3><div style="overflow:auto"><table class="dtable"><tr><th>Поле</th><th>D₁, мм</th><th>D₂, мм</th></tr>${rows(ins,'internal')}</table></div><div class="note">Определитель проверяет измеренный размер сразу по нескольким практическим полям: наружная 6g/6h; внутренняя 6H/7H/8H. 7H и 8H не считаются «хуже» 6H — это отдельные поля допуска по ГОСТ 16093-2004.</div>`}
function limitsTables(t){function tab(title,obj){let rows=Object.entries(obj||{}).map(([c,v])=>`<tr><td><b>${c}</b></td><td>${fmt(v.major_min)} … ${fmt(v.major_max)}</td><td>${fmt(v.pitch_min)} … ${fmt(v.pitch_max)}</td><td>${fmt(v.minor_min)} … ${fmt(v.minor_max)}</td></tr>`).join('');return rows?`<h3>${title}</h3><div style="overflow:auto"><table class="dtable"><tr><th>Класс</th><th>${title.startsWith('Наруж')?'d':'D'}, мм</th><th>${title.startsWith('Наруж')?'d₂':'D₂'}, мм</th><th>${title.startsWith('Наруж')?'d₁':'D₁'}, мм</th></tr>${rows}</table></div>`:''}return tab('Наружная резьба',t.external)+tab('Внутренняя резьба',t.internal)}
$('back').onclick=()=>showPage(prevPage);$('totalN').textContent=THREADS.length;showPage('reference');
// Rebuild the visible representation when rotation crosses the CSS breakpoint.
const referenceMedia=window.matchMedia('(max-width:760px)');
function updateReferenceLayout(){if($('reference').classList.contains('on'))renderReference()}
if(referenceMedia.addEventListener)referenceMedia.addEventListener('change',updateReferenceLayout);
else referenceMedia.addListener(updateReferenceLayout);
